BEGIN;

ALTER TABLE candidat
  ADD COLUMN IF NOT EXISTS date_revue DATE,
  ADD COLUMN IF NOT EXISTS date_revue_modifiee_par VARCHAR(50),
  ADD COLUMN IF NOT EXISTS date_revue_modifiee_le DATE;

ALTER TABLE fiche_de_voeux
  ADD COLUMN IF NOT EXISTS verrouille BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS verrouille_par VARCHAR(50),
  ADD COLUMN IF NOT EXISTS date_verrouillage DATE;

ALTER TABLE user_
  ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

COMMIT;